- name: "create directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "extract zipped file"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Start app
  command: |
      npm install
      pm2 stop default
      pm2 start npm -- start 